import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";
import path from "node:path";

const dbUrl = process.env["DATABASE_URL"] ?? "file:./dev.db";
const dbPath = dbUrl.startsWith("file:")
  ? dbUrl.replace("file:", "").replace(/^\.\//, "")
  : dbUrl;
const absoluteDbPath = path.resolve(dbPath);

const adapter = new PrismaBetterSqlite3({ url: absoluteDbPath });
const prisma = new PrismaClient({ adapter });

async function main() {
  const workspace = await prisma.workspace.upsert({
    where: { id: "default-workspace" },
    update: { name: "\u9ED8\u8BA4\u5DE5\u4F5C\u533A" },
    create: {
      id: "default-workspace",
      name: "\u9ED8\u8BA4\u5DE5\u4F5C\u533A",
    },
  });
  console.log("Seeded workspace:", workspace.id);

  const existingClientSpace = await prisma.clientSpace.findFirst({
    where: { workspaceId: "default-workspace" },
  });

  if (!existingClientSpace) {
    const clientSpace = await prisma.clientSpace.create({
      data: {
        workspaceId: "default-workspace",
        clientName: "\u793A\u4F8B\u5BA2\u6237",
        brandName: "\u793A\u4F8B\u54C1\u724C",
        region: "cn",
        defaultLanguage: "zh-CN",
        targetMarkets: JSON.stringify(["\u6DD8\u5B9D/\u5929\u732B", "\u4EAC\u4E1C", "Amazon"]),
      },
    });
    console.log("Seeded clientSpace:", clientSpace.id);

    const brandPack = await prisma.brandPack.create({
      data: {
        clientSpaceId: clientSpace.id,
        brandName: "\u793A\u4F8B\u54C1\u724C",
        brandPrimaryColor: "#FF6B35",
        brandSecondaryColor: "#004E89",
        brandFontPreference: "\u601D\u6E90\u9ED1\u4F53",
        brandTone: "\u5E74\u8F7B\u6D3B\u529B\u3001\u4E13\u4E1A\u53EF\u4FE1\u8D56",
        brandForbiddenWords: JSON.stringify(["\u5047\u8D27", "\u4F4E\u7AEF", "\u52A3\u8D28"]),
        brandVisualBoundary: "\u4E0D\u4F7F\u7528\u6E10\u53D8\u80CC\u666F\uFF0C\u4FDD\u6301\u7B80\u6D01\u98CE\u683C",
      },
    });
    console.log("Seeded brandPack:", brandPack.id);

    await prisma.seriesPack.create({
      data: {
        clientSpaceId: clientSpace.id,
        brandPackId: brandPack.id,
        seriesName: "\u65D7\u8230\u7CFB\u5217",
        styleLockText: "\u73B0\u4EE3\u6781\u7B80\u98CE\u683C\uFF0C\u767D\u5E95\u4EA7\u54C1\u56FE\uFF0C\u67D4\u548C\u4FA7\u5149\uFF0C\u65E0\u9634\u5F71\u8FC7\u6E21",
        fixedPalette: JSON.stringify(["#FF6B35", "#004E89", "#F7F7F7", "#333333"]),
        backgroundSystem: "\u7EAF\u767D\u80CC\u666F RGB(255,255,255)",
        lightingSystem: "45\u00B0 \u4FA7\u5149 + \u9876\u90E8\u67D4\u5149\u7BB1\uFF0C\u8272\u6E29 5500K",
        defaultBundleStructure: JSON.stringify({
          main_white: { required: true, anchor: true },
          feature: { required: true },
          scene: { required: false },
          spec: { required: false },
        }),
        defaultReviewThreshold: "B",
      },
    });
    console.log("Seeded seriesPack complete");
  } else {
    console.log("Seed data already exists, skipping.");
  }

  console.log("Seeding 10 platform rule packs...");

  const platformRules = [
    {
      platformName: "TAOBAO_TMALL",
      platformRegion: "CN",
      platformType: "marketplace",
      defaultLanguage: "zh-CN",
      maxImages: 5,
      mainImageRatio: "1:1",
      mainImageSize: "800x800",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 3.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: true,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["zh-CN"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_text", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([
        "最好", "第一", "唯一", "顶级", "国家级",
        "7天见效", "永久有效", "治疗", "治愈",
      ]),
      absoluteTermsForbidden: true,
      medicalTermsForbidden: true,
      exportFileNamingRule: "{product_name}_{slot}.{ext}",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: JSON.stringify({ maxLines: 0, maxChars: 0, fontRequirements: "" }),
      forbiddenElements: JSON.stringify(["水印", "边框", "第三方Logo", "虚假认证标志", "二维码"]),
      priceOverlayZone: JSON.stringify({ x: 0, y: 0, width: 200, height: 100, description: "平台价格叠加区" }),
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "JD",
      platformRegion: "CN",
      platformType: "marketplace",
      defaultLanguage: "zh-CN",
      maxImages: 6,
      mainImageRatio: "1:1",
      mainImageSize: "800x800",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 2.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: true,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["zh-CN"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_text", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify(["最好", "第一", "唯一", "顶级", "国家级"]),
      absoluteTermsForbidden: true,
      medicalTermsForbidden: true,
      exportFileNamingRule: "{product_name}_{slot}.{ext}",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "PINDUODUO",
      platformRegion: "CN",
      platformType: "marketplace",
      defaultLanguage: "zh-CN",
      maxImages: 10,
      mainImageRatio: "1:1",
      mainImageSize: "740x352",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 2.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: true,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["zh-CN"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_text", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: false },
        { slotType: "compare", required: true },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify(["最好", "第一", "唯一"]),
      absoluteTermsForbidden: true,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.{ext}",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "DOUYIN",
      platformRegion: "CN",
      platformType: "social",
      defaultLanguage: "zh-CN",
      maxImages: 5,
      mainImageRatio: "1:1",
      mainImageSize: "800x800",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 3.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: true,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: 8,
      supportedLanguagesForPromptText: JSON.stringify(["zh-CN"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_text", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify(["最好", "第一", "唯一", "国家级"]),
      absoluteTermsForbidden: true,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.{ext}",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: JSON.stringify({ maxLines: 2, maxChars: 16, fontRequirements: "醒目字体，叠加于产品上方或下方" }),
      forbiddenElements: JSON.stringify(["水印", "边框", "虚假Logo", "二维码"]),
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "非必须", textAllowed: true, textLimit: "≤8字" }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "AMAZON",
      platformRegion: "global",
      platformType: "marketplace",
      defaultLanguage: "en",
      maxImages: 9,
      mainImageRatio: "1:1",
      mainImageSize: "2000x2000",
      allowedFormats: JSON.stringify(["JPEG", "PNG", "TIFF"]),
      maxFileSizeMb: 10.0,
      whiteBackgroundRequired: true,
      textAllowedOnMainImage: false,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_white", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: false },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.jpg",
      whiteBackgroundToleranceR: 255,
      whiteBackgroundToleranceG: 255,
      whiteBackgroundToleranceB: 255,
      textConstraints: JSON.stringify({ maxLines: 0, maxChars: 0, fontRequirements: "严格禁止" }),
      forbiddenElements: JSON.stringify(["文字", "水印", "边框", "Logo", "任何叠加元素"]),
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "必须纯白", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "EBAY",
      platformRegion: "global",
      platformType: "marketplace",
      defaultLanguage: "en",
      maxImages: 12,
      mainImageRatio: "1:1",
      mainImageSize: "1600x1600",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 7.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: false,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_white", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: false },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.jpg",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "ETSY",
      platformRegion: "global",
      platformType: "marketplace",
      defaultLanguage: "en",
      maxImages: 10,
      mainImageRatio: "1:1",
      mainImageSize: "2000x2000",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 10.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: false,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_white", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.jpg",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "SHOPIFY",
      platformRegion: "global",
      platformType: "independent",
      defaultLanguage: "en",
      maxImages: 8,
      mainImageRatio: "1:1",
      mainImageSize: "2048x2048",
      allowedFormats: JSON.stringify(["JPG", "PNG", "WebP", "GIF"]),
      maxFileSizeMb: 20.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: true,
      watermarkAllowed: true,
      borderAllowed: true,
      logoAllowed: true,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_text", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.{ext}",
      whiteBackgroundToleranceR: 240,
      whiteBackgroundToleranceG: 240,
      whiteBackgroundToleranceB: 240,
      textConstraints: JSON.stringify({ maxLines: 3, maxChars: 50, fontRequirements: "" }),
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "非必须", textAllowed: true, watermarkAllowed: true, borderAllowed: true }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "TIKTOK_SHOP",
      platformRegion: "global",
      platformType: "social",
      defaultLanguage: "en",
      maxImages: 9,
      mainImageRatio: "1:1",
      mainImageSize: "600x600",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 5.0,
      whiteBackgroundRequired: true,
      textAllowedOnMainImage: false,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_white", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: true },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.jpg",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
    {
      platformName: "ALIEXPRESS",
      platformRegion: "global",
      platformType: "marketplace",
      defaultLanguage: "en",
      maxImages: 6,
      mainImageRatio: "1:1",
      mainImageSize: "800x800",
      allowedFormats: JSON.stringify(["JPG", "PNG"]),
      maxFileSizeMb: 5.0,
      whiteBackgroundRequired: false,
      textAllowedOnMainImage: false,
      watermarkAllowed: false,
      borderAllowed: false,
      logoAllowed: false,
      maxOverlayTextLength: null,
      supportedLanguagesForPromptText: JSON.stringify(["en"]),
      supportedSlots: JSON.stringify([
        { slotType: "main_white", required: true },
        { slotType: "feature", required: true },
        { slotType: "scene", required: false },
        { slotType: "compare", required: false },
        { slotType: "spec", required: false },
        { slotType: "trust", required: false },
      ]),
      forbiddenWords: JSON.stringify([]),
      absoluteTermsForbidden: false,
      medicalTermsForbidden: false,
      exportFileNamingRule: "{product_name}_{slot}.jpg",
      whiteBackgroundToleranceR: 250,
      whiteBackgroundToleranceG: 250,
      whiteBackgroundToleranceB: 250,
      textConstraints: "{}",
      forbiddenElements: "[]",
      priceOverlayZone: "{}",
      exportDirectoryStructure: JSON.stringify({ images: "/", manifest: true, readme: true }),
      exportSortOrder: JSON.stringify(["main_white", "main_text", "feature", "scene", "spec", "compare", "trust"]),
      deliveryNotes: JSON.stringify({ whiteBg: "建议白底", textAllowed: false }),
      versions: JSON.stringify([{ version: "1.0.0", changedBy: "system", changeNote: "Phase 1a baseline", createdAt: "2026-05-19" }]),
    },
  ];

  for (const rule of platformRules) {
    await prisma.platformRulePack.upsert({
      where: { platformName: rule.platformName },
      update: rule,
      create: rule,
    });
    console.log(`  Seeded platform rule: ${rule.platformName}`);
  }

  console.log("All 10 platform rules seeded.");

  console.log("Seeding ProviderConfig...");

  const providerConfigs = [
    {
      id: "provider-openai-official",
      name: "OpenAI 官方",
      type: "openai",
      apiKey: process.env["OPENAI_API_KEY"] ?? "sk-placeholder",
      baseURL: null,
      priority: 1,
      isActive: true,
      config: JSON.stringify({ model: "dall-e-3", defaultSize: "1024x1024" }),
    },
    {
      id: "provider-apimart",
      name: "apimart.ai",
      type: "apimart",
      apiKey: process.env["APIMART_API_KEY"] ?? "sk-apimart-placeholder",
      baseURL: "https://api.apimart.ai/v1",
      priority: 2,
      isActive: false,
      config: JSON.stringify({ model: "dall-e-3", defaultSize: "1024x1024" }),
    },
  ];

  for (const config of providerConfigs) {
    await prisma.providerConfig.upsert({
      where: { id: config.id },
      update: {
        name: config.name,
        type: config.type,
        apiKey: config.apiKey,
        baseURL: config.baseURL,
        priority: config.priority,
        isActive: config.isActive,
        config: config.config,
      },
      create: config,
    });
    console.log(`  Seeded provider: ${config.name}`);
  }

  console.log("ProviderConfig seeding complete.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
